install: true
sudo: required
services:
  - docker
deploy:
  - provider: elasticbeanstalk
    only_create_app_version: "true"
    region: "ap-southeast-2"
    app: "Pact Broker"
    env: "pact-broker-prod"
    bucket_name: "pact-eb-deployments"
    skip_cleanup: true
    zip_file: "build/distributions/eb.zip"
    on:
      all_branches: true
      tags: true
